# Generated by Django 4.1.7 on 2023-03-07 21:56

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.CharField(db_index=True, default=app.utils.generate_token, editable=False, max_length=256, unique=True)),
                ('access_token', models.CharField(max_length=256)),
                ('expires_in', models.PositiveSmallIntegerField(default=app.utils.next_two_weeks)),
                ('scope', models.CharField(max_length=1024)),
                ('token_type', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
