# Generated by Django 4.1.7 on 2023-03-13 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='app.sallauser'),
        ),
        migrations.CreateModel(
            name='SallaStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salla_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('avatar', models.URLField(blank=True, max_length=512, null=True)),
                ('plan', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('verified', models.BooleanField(default=True)),
                ('currency', models.CharField(blank=True, max_length=16, null=True)),
                ('domain', models.URLField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('licenses', models.JSONField(default=dict)),
                ('social', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='app.sallauser')),
            ],
        ),
    ]
