# Generated by Django 4.1.7 on 2023-03-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_account_user_sallastore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGPTLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=512)),
                ('total_tokens', models.PositiveSmallIntegerField(default=0)),
                ('answer', models.TextField()),
                ('full_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
