# Generated by Django 4.1.7 on 2023-03-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='refresh_token',
            field=models.CharField(default='123', max_length=256),
            preserve_default=False,
        ),
    ]
