# Generated by Django 4.1.7 on 2023-04-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SallaWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=128)),
                ('merchant_id', models.CharField(max_length=64)),
                ('data', models.JSONField(default=dict)),
                ('response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
