# Generated by Django 4.1.7 on 2023-05-05 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_chatgptlog_chatgptresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprompt',
            old_name='chat_gpt_log',
            new_name='chat_gpt_response',
        ),
    ]
