# Generated by Django 4.1.7 on 2023-05-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_chat_gpt_log_userprompt_chat_gpt_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprompt',
            name='is_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprompt',
            name='product_id',
            field=models.CharField(db_index=True, default='undefined', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprompt',
            name='prompt_type',
            field=models.CharField(choices=[('title', 'title'), ('description', 'description'), ('seo_title', 'seo_title'), ('seo_description', 'seo_description')], default='description', max_length=32),
            preserve_default=False,
        ),
    ]
