# Generated by Django 4.1.7 on 2023-05-13 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userprompt_is_accepted_userprompt_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SallaUserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(max_length=32)),
                ('plan_name', models.CharField(max_length=32)),
                ('plan_period', models.DurationField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('gpt_prompts_limit', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='app.sallauser')),
            ],
        ),
    ]
