# Generated by Django 4.1.7 on 2023-05-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_sallausersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='sallausersubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sallausersubscription',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
    ]
