# Generated by Django 4.1.7 on 2023-05-17 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_sallausersubscription_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprompt',
            name='chat_gpt_response',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_prompt', to='app.chatgptresponse'),
        ),
    ]
