# Generated by Django 4.1.7 on 2023-07-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_userprompt_chat_gpt_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='sallausersubscription',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
