# Generated by Django 4.1.7 on 2023-04-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('head', models.TextField(blank=True, null=True)),
                ('custom_css', models.TextField(blank=True, null=True)),
                ('custom_js', models.TextField(blank=True, null=True)),
                ('md', models.TextField(blank=True, null=True)),
                ('html', models.TextField(blank=True, null=True)),
                ('is_nav', models.BooleanField(default=False)),
                ('nav_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
