# Generated by Django 4.1.7 on 2023-04-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteServe', '0003_chatgptprompttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgptprompttemplate',
            name='type',
            field=models.CharField(choices=[('title', 'title'), ('description', 'description'), ('seo_title', 'seo_title'), ('seo_description', 'seo_description')], max_length=200),
        ),
    ]
