# Generated by Django 4.1.7 on 2023-05-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteServe', '0005_alter_chatgptprompttemplate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgptprompttemplate',
            name='template',
            field=models.TextField(verbose_name='Allowed labels are {product_name}, {product_description}, {product_seo_title}, {keywords}, or {brand_name} || Keep in mind the DEPENDENCIES when choose the labels.'),
        ),
    ]
